### ISSUE TITLE
JSON decoder error when getting candle data

### ISSUE THREAD

**Issue by judasbenhur** [gastonmichel/pyfinex#1]
Occasionally when getting candle 1 minute data the JSON decoder will output the following error:

> Traceback (most recent call last):
>     resp = pyfinex.v2.public.candles(Symbol=symbol, TimeFrame='1m', Section='hist', limit=length_minutes, start=start, end=end, sort=1)
>   File "/home/tobi/anaconda3/envs/env_one/lib/python3.6/site-packages/pyfinex-1.0.1-py3.6.egg/pyfinex/v2/public.py", line 57, in candles
>   File "/home/tobi/anaconda3/envs/env_one/lib/python3.6/site-packages/pyfinex-1.0.1-py3.6.egg/pyfinex/api.py", line 45, in request
>   File "/home/tobi/anaconda3/envs/env_one/lib/python3.6/site-packages/requests/models.py", line 896, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/home/tobi/anaconda3/envs/env_one/lib/python3.6/json/__init__.py", line 354, in loads
>     return _default_decoder.decode(s)
>   File "/home/tobi/anaconda3/envs/env_one/lib/python3.6/json/decoder.py", line 339, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/home/tobi/anaconda3/envs/env_one/lib/python3.6/json/decoder.py", line 357, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

This happens when iterating through a long list of historic data. Usually after 300 or higher API calls of 1000 data points.

**Comment by gastonmichel** [comment]
Hi, it seems like a bitfinex.com server side error.
Are you throttling your requests to a max of 90 per minute as bitfinex allow?
Everything indicates that the response is empty. I will add an empty response error handling, so you can catch it.

Thanks to report!

**Comment by judasbenhur** [comment]
i'm requesting 1000 entries every 5 seconds for a period of two years. More or less. It runs fine but will output this error above after a random number of calls. Its not always after the 500th call. Sometimes its the 300th, the 600th or the 1100th call.

**Comment by gastonmichel** [comment]
I identified a bug (no sure if it is the cause): pyfinex.api.request() was trying to .json() the response before cheking the response status.

Aditionally I added a BitfinexEmptyResponse so you can catch it.

Please update pyfinex via pip:
`pip install pyfinex==1.0.3`

Remember that bitfinex api v2 is beta, and not well documented :-(
